-name: Installing nginx
 host: web
 task:
 -name: install nginx server
  ansible.builtin.package:
   name : nginx
   status : present
 -name: starting nginx
  ansible.builtin.service:
   name: nginx
   status: started
   enabled: yes